
services:
  # ganache:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   ports:
  #     - "8545:8545"
  #   volumes:
  #     - ./ganache:/data
  #   working_dir: /data
  #   environment:
  #     - NETWORK_ID=5777
  #     - DEFAULT_BALANCE_ETHER=1000000000000000000000
  #     - BLOCK_TIME=1
  #     - GAS_LIMIT=8000000
  #     - FORK_URL=http://localhost:8545
  #     - FORK_BLOCK_NUMBER=0

  getter:
    image: python:latest
    container_name: getter_service
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - ./backend_local:/app
    command: /bin/bash -c "pip install -r requirements.txt && python3 app.py"


  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
  nextjs:
    image: node:latest
    container_name: nextjs_app
    working_dir: /app
    stdin_open: true
    command: npm run start
    volumes:
      - ./wrap-frontend:/app
    ports:
      - "3000:3000"
    #environment:
    #  - NODE_ENV=production
  # Uncomment if you want to use a local .env file
  # env_file:
  #   - ./frontend/.env
